server:
  port: 8082
debug: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/he?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  mvc:
    view:
      prefix: /WEB-INF/templates/
      suffix: .jsp

  devtools:
    restart:
      enabled: true  #设置开启热部署
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效